### ISSUE TITLE
How do we set up CMakeLists.txt without using makeflile to rebuild with cmake + Ninja

### ISSUE THREAD

**Issue by 3038922** [Aggie-FIRST-Robotics/VEX-U_2018-V5#30]
How do we set up CMakeLists. TXT without using makeflile to rebuild with cmake + Ninja?

**Comment by Buzzec** [comment]
CMakeList.txt is only for the IDE we use called CLion, if you wish to build or upload use the commands from pros. Also this is not finished software, we are actively working on it and is specific to our robot implementation.

**Comment by 3038922** [comment]
thank you
